# Generated by Django 5.2.5 on 2026-01-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_image_remove_profile_is_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
