# Generated by Django 6.0 on 2025-12-31 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_details', models.TextField()),
                ('nid_number', models.CharField(max_length=20)),
                ('products', models.ManyToManyField(blank=True, related_name='vendors', to='products.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
