# Generated by Django 6.0 on 2025-12-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='products',
        ),
    ]
