# Generated by Django 5.2.5 on 2026-02-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_cart_id_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
